//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace palyazatCucc
{
    using System;
    using System.Collections.Generic;
    
    public partial class palyazatokAllapota
    {
        public int id { get; set; }
        public Nullable<int> keretosszeg { get; set; }
        public Nullable<int> szamlakSzama { get; set; }
        public Nullable<int> szamlakOsszege { get; set; }
    }
}
