//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace palyazatCucc
{
    using System;
    using System.Collections.Generic;
    
    public partial class szamla
    {
        public int id { get; set; }
        public string szamlaszam { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public Nullable<int> ertek { get; set; }
        public Nullable<int> palyazatId { get; set; }
        public string koltsegtipusId { get; set; }
    
        public virtual koltsegtipus koltsegtipus { get; set; }
        public virtual palyazat palyazat { get; set; }
    }
}
